statefulset:
  name: kafka
  namespace: kafka
  replicas: 3
  appname: kafka-app
  serviceName: kafka-svc
  image: doughgle/kafka-kraft
  ports:
    - name: kafka
      containerPort: 9092
    - name: controller
      containerPort: 9093
  env:
    - name: REPLICAS
      value: '3'
    - name: SERVICE
      value: kafka-svc
    - name: NAMESPACE
      value: kafka
    - name: SHARE_DIR
      value: /mnt/kafka
    - name: CLUSTER_ID
      value: bXktY2x1c3Rlci0xMjM0NQ==
    - name: DEFAULT_REPLICATION_FACTOR
      value: '3'
    - name: DEFAULT_MIN_INSYNC_REPLICAS
      value: '2'

service:
  name: kafka-svc
  namespace: kafka
  replicas: 3
  appname: kafka-app
  type: NodePort
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
      nodePort: 30092
      containerName: consumer

consumer:
  namespace: kafka
  name: kafka-consumer
  bootstrapServers: kafka-svc.kafka:9092
  replicas: 3
  image: bitnami/kafka:3.7.0
  topic: new-demo-topic
  extraArgs: "--from-beginning"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

keda:
  namespace: kafka
  enabled: true
  bootstrapServers: kafka-svc.kafka:9092
  topic: new-demo-topic
  consumerGroup: my-consumer-group
  lagThreshold: "10"
  minReplicaCount: 3
  maxReplicaCount: 5
  ScaledObject: kafka-consumer
