apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: consumer
          image: bitnami/kafka:3.7.0
          command:
            - "sh"
            - "-c"
            - |
              kafka-console-consumer.sh --bootstrap-server kafka-svc.kafka:9092 --topic new-demo-topic --from-beginning