apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.consumer.name }}
  namespace: {{ .Values.consumer.namespace }}
spec:
  replicas: {{ .Values.consumer.replicas | default 3}}
  selector:
    matchLabels:
      app: {{ .Values.consumer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.consumer.name }}
    spec:
      containers:
        - name: consumer
          image: bitnami/kafka:3.7.0
          command:
            - "sh"
            - "-c"
            - |
              kafka-console-consumer.sh --bootstrap-server kafka-svc.kafka:9092 --topic new-demo-topic --from-beginning
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
     