apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.consumer.name }}
  namespace: {{ .Values.consumer.namespace }}
spec:
  replicas: {{ .Values.consumer.replicas | default 3}}
  selector:
    matchLabels:
      app: {{ .Values.consumer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.consumer.name }}
    spec:
      containers:
        - name: {{ .Values.consumer.name }}
          image: {{ .Values.consumer.image | default "bitnami/kafka:3.7.0" }}
          command:
            - "sh"
            - "-c"
            - |
              kafka-console-consumer.sh --bootstrap-server kafka-svc.kafka:9092 --topic {{ .Values.consumer.topic | default "new-demo-topic" }} --from-beginning {{ .Values.consumer.extraArgs | default "" }}
          resources:
            requests:
              cpu: {{ .Values.consumer.resources.requests.cpu | default "200m" }}
              memory: {{ .Values.consumer.resources.requests.memory | default "256Mi" }}
            limits:
              cpu: {{ .Values.consumer.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.consumer.resources.limits.memory | default "512Mi" }}
