apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: producer
          image: bitnami/kafka:3.7.0
          command:
            - "sh"
            - "-c"
            - |
              while true; do
                echo "Hello from new log producer at $(date)" | \
                kafka-console-producer.sh --broker-list kafka-svc.kafka:9092 --topic new-demo-topic
                sleep 5
              done