apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.consumer.name }}
  namespace: {{ .Values.consumer.namespace }}
spec:
  replicas: {{ .Values.consumer.replicas | default 3}}
  selector:
    matchLabels:
      app: {{ .Values.consumer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.consumer.name }}
    spec:
      containers:
        - name: consumer
          image: bitnami/kafka:3.7.0
          command: ["kafka-console-consumer.sh"]
          args:
            - "--bootstrap-server"
            - "{{ .Values.consumer.bootstrapServers }}"
            - "--topic"
            - "{{ .Values.consumer.topic }}"
            - "--group"
            - "{{ .Values.consumer.consumerGroup }}"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
     